name: Publish Website

on: push

jobs:
  Fast-FTP-Action:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Fast FTP Action
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ftp.imtheluckiest.com
          username: rootpublichtml@imtheluckiest.com
          password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: "poster-prompt-generator/"
          local_dir: "dist/"
